services:

  postgres:
    image: postgres:17
    container_name: eventhub-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: eventhub
      POSTGRES_USER: eventhub
      POSTGRES_PASSWORD: eventhub123

    ports:
      - "5432:5432"

    volumes:
      - eventhub_postgres_data:/var/lib/postgresql/data

volumes:
  eventhub_postgres_data: